# -*- coding: utf-8 -*-
"""SENAI-Python-Aula4-LISTA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B2J2zejmmrn2F5zLTXEyeeS6MZ6Z6R6y

## Listas
"""

nomes = ['vitor' , 'caroline' , 'caio' , 'luana' , 'juliana']
#           0           1         2         3           4
nomes[0]
# vitor

nomes[4]
# juliana

nomes[-1]
# juliana

nomes[1:4]
# carol caio luana

nomes[::-1]
# juliana luana caio carolina vitor

"""# Type e len"""

nomeDaLista = ['conteudo1' , 'conteudo2' , 'conteudo3' , 'conteudo4' , 'conteudo5']

print(type(nomeDaLista))  # <==========AQUI

print(len(nomeDaLista))  # <==========AQUI

print(nomeDaLista[4])

"""# Alteracao"""

nomeDaLista = ['conteudo1' , 'conteudo2' , 'conteudo3' , 'conteudo4' , 'conteudo5']

print(nomeDaLista)

nomeDaLista[1] = 'ALterado'  # <==========AQUI
print()

print(nomeDaLista)

"""# Append"""

nomeDaLista = ['conteudo1' , 'conteudo2' , 'conteudo3' , 'conteudo4' , 'conteudo5']

print(nomeDaLista)

nomeDaLista.append('conteudo6')  # <==========AQUI
print()

print(nomeDaLista)

"""# Insert"""

nomeDaLista = ['conteudo1' , 'conteudo2' , 'conteudo3' , 'conteudo4' , 'conteudo5']

print(nomeDaLista)

nomeDaLista.insert(1 , 'conteudoCoringa')  # <==========AQUI
print()

print(nomeDaLista)

"""# Remove"""

nomeDaLista = ['conteudo1' , 'conteudo2' , 'conteudo3' , 'conteudo4' , 'conteudo5']

print(nomeDaLista)

nomeDaLista.remove('conteudo1')  # <==========AQUI
print()

print(nomeDaLista)

"""# Pop"""

nomeDaLista = ['conteudo1' , 'conteudo2' , 'conteudo3' , 'conteudo4' , 'conteudo5']

print(nomeDaLista)

nomeDaLista.pop(-1) # <==========AQUI
print()

print(nomeDaLista)

list(range(10))

"""# Sort e Reverse"""

livros = ['Java' , 'SQLServer' , 'Delphi' , 'Python' , 'Android']

print(livros)

livros.sort() # <==========AQUI
print()

print(livros)

livros.reverse() # <==========AQUI
print()

print(livros)

"""## Tuplas"""

times_sp = ('Santos' , 'Palmeiras' , 'Corinthians' , 'Sao Paulo') #Tupla

print(type(times_sp))

print(times_sp)

obj_string = ('tesoura')
obj_tupla = ('tesoura' ,)

print(type(obj_string))
print(type(obj_tupla))

"""# min max e sum"""

numeros = [15 , 5 , 0 , 20 , 10 ]

print(min(numeros)) # <==========AQUI
print(max(numeros)) # <==========AQUI

livros = ['Java' , 'SQLServer' , 'Delphi' , 'Python' , 'Android']

print(min(livros)) # <==========AQUI
print(max(livros)) # <==========AQUI

numeros = [1 , 3 , 6]

print(sum(numeros))

media = sum(numeros) / len(numeros) # <==========AQUI

print(f'{media}')

"""# List Comprehension"""

quadrados = [x ** 2 for x in range(1, 11)]

print(quadrados)
print()

numeros = [1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 , 10]
apenas_pares = [x for x in numeros if x % 2 == 0]

print(apenas_pares)
print()

quadrados_tuplas = [(x, x ** 2) for x in range(1 , 6)]
print(quadrados_tuplas)

"""## Dicionario"""

meu_dicionario = {} # <==========AQUI como e a estrutura do dicionario

aluno = {
  'nome' : 'Joao',
  'idade' : 25,
  'curso' : 'Ciencia de Dados'
}

print(aluno['nome'])

aluno['nota_final'] = 85 # <==========AQUI Adicionando chave no dicionario

print(aluno['idade'])

print(aluno)

aluno = {
  'nome' : 'Joao',
  'idade' : 25,
  'curso' : 'Ciencia de Dados',
  'notas' : {'matematica' : 90 , 'historia' : 85 , 'ingles' : 88}
}

print('Intervalo sobre as chaves: ')
for chave in aluno:
  print(chave)

print()
#===================================================
aluno = {
  'nome' : 'Joao',
  'idade' : 25,
  'curso' : 'Ciencia de Dados',
  'notas' : {'matematica' : 90 , 'historia' : 85 , 'ingles' : 88}
}

print('Intervalo sobre as chaves: ')
for chave, valor in aluno.items():
  print(chave , ':' , valor)

print()
#===================================================
aluno = {
  'nome' : 'Joao',
  'idade' : 25,
  'curso' : 'Ciencia de Dados',
  'notas' : {'matematica' : 90 , 'historia' : 85 , 'ingles' : 88}
}

print('Notas: ')
for disciplina, nota in aluno['notas'].items():
  print(disciplina , ':' , nota)

turma_matematica = {
  1:{'nome' : 'Marcos' , 'nota' : 70},
  2:{'nome' : 'Maria' , 'nota' : 80},
  3:{'nome' : 'Manuel' , 'nota' : 60},
  4:{'nome' : 'Miriam' , 'nota' : 75}
}

for id in turma_matematica:
  print(turma_matematica[id]['nota'])
0
print()

turma_matematica = {
  1:{'nome' : 'Marcos' , 'nota' : 70},
  2:{'nome' : 'Maria' , 'nota' : 80},
  3:{'nome' : 'Manuel' , 'nota' : 60},
  4:{'nome' : 'Miriam' , 'nota' : 75}
}

for id in turma_matematica:
  print(turma_matematica[id]['nome'])